server:
  port: 8082

spring:
  application:
    name: user-service
  autoconfigure:
    exclude: org.springframework.boot.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000
