package com.volna.inventory_service.service;
import com.volna.inventory_service.dto.inventory.*;import com.volna.inventory_service.entity.InventoryItem;import com.volna.inventory_service.enums.InventoryStatus;import com.volna.inventory_service.exception.*;import com.volna.inventory_service.repository.InventoryItemRepository;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;
@Service @Transactional public class InventoryItemService{private final InventoryItemRepository repo;private final InventoryRestaurantAccessService access;public InventoryItemService(InventoryItemRepository r,InventoryRestaurantAccessService a){repo=r;access=a;}
 public Page<InventoryItemResponse> getAll(UUID u,String search,Pageable p){UUID r=access.restaurant(u);return (search==null||search.isBlank()?repo.findByRestaurantId(r,p):repo.findByRestaurantIdAndNameContainingIgnoreCase(r,search,p)).map(this::map);}
 public InventoryItemResponse get(UUID u,Long id){return map(find(u,id));}
 public InventoryItemResponse create(UUID u,CreateInventoryItemRequest q){UUID r=access.restaurant(u);if(repo.existsBySkuAndRestaurantId(q.getSku(),r))throw new BadRequestException("SKU already exists");InventoryItem x=new InventoryItem();x.setRestaurantId(r);x.setName(q.getName());x.setSku(q.getSku());x.setCategory(q.getCategory());x.setUnit(q.getUnit());x.setStockLevel(q.getStockLevel());x.setMinimumStock(q.getMinimumStock());x.setUnitCost(q.getUnitCost());x.setExpiryDate(q.getExpiryDate());x.setSupplier(q.getSupplier());return map(repo.save(x));}
 public InventoryItemResponse update(UUID u,Long id,UpdateInventoryItemRequest q){InventoryItem x=find(u,id);x.setName(q.getName());x.setCategory(q.getCategory());x.setUnit(q.getUnit());x.setMinimumStock(q.getMinimumStock());x.setUnitCost(q.getUnitCost());x.setExpiryDate(q.getExpiryDate());x.setSupplier(q.getSupplier());return map(repo.save(x));}
 public void delete(UUID u,Long id){repo.delete(find(u,id));}
 public InventoryItemResponse adjust(UUID u,Long id,StockAdjustmentRequest q){InventoryItem x=find(u,id);BigDecimal n=x.getStockLevel().add(q.getQuantity());if(n.compareTo(BigDecimal.ZERO)<0)throw new BadRequestException("Stock cannot become negative");x.setStockLevel(n);return map(repo.save(x));}
 public List<InventoryItemResponse> byStatus(UUID u,InventoryStatus s){return repo.findByRestaurantIdAndStatus(access.restaurant(u),s).stream().map(this::map).toList();}
 private InventoryItem find(UUID u,Long id){return repo.findByIdAndRestaurantId(id,access.restaurant(u)).orElseThrow(()->new ResourceNotFoundException("Inventory item not found"));}
 private InventoryItemResponse map(InventoryItem x){return new InventoryItemResponse(x.getId(),x.getName(),x.getSku(),x.getCategory(),x.getUnit(),x.getStockLevel(),x.getMinimumStock(),x.getUnitCost(),x.getExpiryDate(),x.getStatus(),x.getSupplier());}}
