package com.volna.customerorder.entity;
public enum OrderStatus { CREATED,PAYMENT_PENDING,PAID,RESTAURANT_ACCEPTED,PREPARING,READY_FOR_PICKUP,RIDER_ASSIGNED,PICKED_UP,OUT_FOR_DELIVERY,DELIVERED,CANCELLED,PAYMENT_FAILED }
